version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.3
    volumes:
      - weaviate_data:/data
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
  backend:
    image: marvinkarhan/cpd:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:eu-central-1:451753274529:secret:dockerhubAccessToken-LoFLqv
    ports:
      - "5000:5000"
    environment:
      WEAVIATE_URL: http://weaviate:8080
      OPEN_AI_API_KEY: "${OPEN_AI_API_KEY}"
volumes:
  weaviate_data:
